### PR TITLE
Update 433mhz_jam.ino

### PR DESCRIPTION
**Pull request by mayaku2go**
Improved the Code a lot ^^

### CODE REVIEW

**Comment by 0xless** [comment]
Hi, thanks for your PR.
It looks good, but I need to test it both on ESP32 and ESP8266 before merging, as soon as I have some time available I'll take care of it.

Thanks again!

**Comment by mayaku2go** [comment]
You're welcome!
I just got rid of every warning the compiler had put out and will update
the code asap ^^

Matteo (0xless) ***@***.***> schrieb am Mi., 17. Apr. 2024,
10:12:

**Comment by 0xless** [comment]
I finally had time to test your PR, found some compatibility issues with ESP8266, but it was a couple of easy fixes.
I'm merging this PR and then fixing one thing or two once that's done.

Thanks for contributing to this project!

**Comment by mayaku2go** [comment]
You're welcome and good to hear ^^
I have only ESP32, sorry for not mentioning it.
Just improoved the webinterface a little bit, now you can select the pulse
width ^^ Have to test it though because I really suck in html XD

Matteo (0xless) ***@***.***> schrieb am Mo., 29. Apr. 2024,
16:39:

**Comment by mayaku2go** [comment]
I just tested the jammer with a duty of 1024 with a BMW car and it didn't
work at all. Unfortunately I don't have a car of my own for testing. Maybe
the tone() function works better. Will test it asap ^^

Matteo (0xless) ***@***.***> schrieb am Mo., 29. Apr. 2024,
16:39:

**Comment by 0xless** [comment]
@mayaku2go do you have an SDR you can use to test the output signal? There are differences in the spectrum between tone to duty cycle methods, but you should check the output of the transmitter, different boards behave slightly differently. Also the specific remote you're testing might not work on 433mhz.

**Comment by mayaku2go** [comment]
Unfortunately not. Only an Oszilloscope for measuring the PWM output. As I
am in Hamburg I could ask the Chaos Computer Club XD
Tried this the first time with an Attiny and a difderent sketch, this
version was working with the BMW car.

Matteo (0xless) ***@***.***> schrieb am Di., 30. Apr. 2024,
21:30:

**Comment by mayaku2go** [comment]
Tested it yesterday very successfully with tone() and a frequency of 20000. Will try to find the corresponding duty cycle.

**Pull request merged**
